name: Build App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_KEY: ${{ secrets.JWT_KEY }}

    steps:
      - uses: actions/checkout@v4


      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Run app
        run: node server.js
        working-directory: server